parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 10.0.0.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 10.0.0.149
        start: 10.0.0.101
    ExternalInterfaceDefaultRoute: 10.0.0.1
    ExternalNetCidr: 10.0.0.0/24
    ExternalNetworkVlanID: 10
    InternalApiAllocationPools:
    -   end: 172.17.1.149
        start: 172.17.1.10
    InternalApiNetCidr: 172.17.1.0/24
    InternalApiNetworkVlanID: 20
    NeutronBridgeMappings: tenant:br-ex
    NeutronExternalNetworkBridge: ''
    NeutronNetworkVLANRanges: tenant:1000:2000
    StorageAllocationPools:
    -   end: 172.17.3.149
        start: 172.17.3.10
    StorageMgmtAllocationPools:
    -   end: 172.17.4.149
        start: 172.17.4.10
    StorageMgmtNetCidr: 172.17.4.0/24
    StorageMgmtNetworkVlanID: 40
    StorageNetCidr: 172.17.3.0/24
    StorageNetworkVlanID: 30
    TenantAllocationPools:
    -   end: 172.17.2.149
        start: 172.17.2.10
    TenantNetCidr: 172.17.2.0/24
    TenantNetworkVlanID: 50
resource_registry:
    OS::TripleO::ControllerDeployedServer::Net::SoftwareConfig: /home/stack/virt/network/three-nics-vlans/controller.yaml
    OS::TripleO::ComputeDeployedServer::Net::SoftwareConfig: /home/stack/virt/network/three-nics-vlans/compute.yaml

